---

- name: Include custom vars
  include_vars: "{{ path_to_db_vars }}"
  tags:
   - mariadb_create 
   - mariadb_copy
   - mariadb_import

- name: Create DB
  mysql_db:
   name: "{{ item }}"
   state: present
  with_items:
   - "{{ dbname }}"
  when: dbstate == 'create'
  tags: mariadb_create

- name: Create DB User
  mysql_user:
   name: "{{ dbuser }}"
   password: "{{ dbuserpass }}"
   priv: "{{ db_user_priv }}" 
   host: "{{ db_user_host }}" 
   state: present
  when: dbstate == 'create'
  tags: mariadb_create

#===========================================

- name: Copy Backup DB
  copy:
   src: "{{ path_to_sqldump }}/{{ dbdump }}"
   dest: /tmp
  when: dbstate == 'import'
  tags: mariadb_copy

- name: Import Backup DB
  mysql_db:
   name: "{{ dbname }}"
   state: import 
   target: /tmp/{{ dbdump }}
  with_items:
   - "{{ dbdump }}"
  when: dbstate == 'import'
  tags: mariadb_import
#  changed_when: 
