---

- name: MariaDB install
  yum: name={{ item }} state=present
  with_items:
   - MySQL-python
   - mariadb-server
  tags: mariadb_install
  notify:
   - mariadb start

- name: mariadb start
  service: name=mariadb state=started enabled=yes
  tags: mariadb_install

- include: db_operations.yml
